/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package application;

import java.io.BufferedReader;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;

/**
 *
 * @author Admin
 */
@SuppressWarnings("ALL")
public class SignUpScreen extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    public SignUpScreen() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        kGradientPanel3 = new keeptoo.KGradientPanel();
        signUpTitle = new javax.swing.JLabel();
        signUpLogIn = new javax.swing.JLabel();
        signUpName = new javax.swing.JLabel();
        signUpNameField = new javax.swing.JTextField();
        signUpPass = new javax.swing.JLabel();
        jPasswordField4 = new javax.swing.JPasswordField();
        signUpCheckBox = new javax.swing.JCheckBox();
        kGradientPanel4 = new keeptoo.KGradientPanel();
        jLabel1 = new javax.swing.JLabel();
        signUpPassField2 = new javax.swing.JPasswordField();
        signUpConfirmPass = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("ProTasker");
        setLocation(new java.awt.Point(0, 0));
        setResizable(false);
        getContentPane().setLayout(new javax.swing.BoxLayout(getContentPane(), javax.swing.BoxLayout.LINE_AXIS));

        kGradientPanel3.setkEndColor(new java.awt.Color(248, 237, 235));
        kGradientPanel3.setkStartColor(new java.awt.Color(252, 249, 190));
        kGradientPanel3.setPreferredSize(new java.awt.Dimension(300, 600));

        signUpTitle.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        signUpTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        signUpTitle.setText("PROJECT: ProTasker");
        signUpTitle.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        signUpTitle.setMaximumSize(new java.awt.Dimension(80, 25));
        signUpTitle.setMinimumSize(new java.awt.Dimension(80, 25));
        signUpTitle.setPreferredSize(new java.awt.Dimension(200, 25));

        signUpLogIn.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        signUpLogIn.setText("Back");
        signUpLogIn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                signUpLogInMouseClicked(evt);
            }
        });

        signUpName.setBackground(new java.awt.Color(255, 255, 255));
        signUpName.setText("  Username");

        signUpNameField.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(248, 200, 200)));
        signUpNameField.setPreferredSize(new java.awt.Dimension(220, 30));
        signUpNameField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                signUpNameFieldActionPerformed(evt);
            }
        });

        signUpPass.setBackground(new java.awt.Color(255, 255, 255));
        signUpPass.setText("  Password");
        signUpPass.setPreferredSize(new java.awt.Dimension(59, 16));

        jPasswordField4.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(255, 220, 169)));
        jPasswordField4.setPreferredSize(new java.awt.Dimension(220, 30));
        jPasswordField4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPasswordField4ActionPerformed(evt);
            }
        });

        signUpCheckBox.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        signUpCheckBox.setForeground(javax.swing.UIManager.getDefaults().getColor("Button.default.borderColor"));
        signUpCheckBox.setBorder(null);
        signUpCheckBox.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        signUpCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                signUpCheckBoxActionPerformed(evt);
            }
        });

        kGradientPanel4.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 255, 255)));
        kGradientPanel4.setkEndColor(new java.awt.Color(255, 220, 169));
        kGradientPanel4.setkGradientFocus(200);
        kGradientPanel4.setkStartColor(new java.awt.Color(248, 200, 200));
        kGradientPanel4.setPreferredSize(new java.awt.Dimension(220, 38));
        kGradientPanel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                kGradientPanel4MouseClicked(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 51, 51));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Sign Up");
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel1.setPreferredSize(new java.awt.Dimension(43, 35));
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });
        jLabel1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jLabel1KeyPressed(evt);
            }
        });

        javax.swing.GroupLayout kGradientPanel4Layout = new javax.swing.GroupLayout(kGradientPanel4);
        kGradientPanel4.setLayout(kGradientPanel4Layout);
        kGradientPanel4Layout.setHorizontalGroup(
            kGradientPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        kGradientPanel4Layout.setVerticalGroup(
            kGradientPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 36, Short.MAX_VALUE)
        );

        signUpPassField2.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(248, 200, 200)));
        signUpPassField2.setPreferredSize(new java.awt.Dimension(220, 30));
        signUpPassField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                signUpPassField2ActionPerformed(evt);
            }
        });

        signUpConfirmPass.setBackground(new java.awt.Color(255, 255, 255));
        signUpConfirmPass.setText("  Confirm Password");
        signUpConfirmPass.setPreferredSize(new java.awt.Dimension(59, 16));

        jLabel2.setForeground(new java.awt.Color(255, 0, 0));

        javax.swing.GroupLayout kGradientPanel3Layout = new javax.swing.GroupLayout(kGradientPanel3);
        kGradientPanel3.setLayout(kGradientPanel3Layout);
        kGradientPanel3Layout.setHorizontalGroup(
            kGradientPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kGradientPanel3Layout.createSequentialGroup()
                .addGroup(kGradientPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(signUpLogIn, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(signUpTitle, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(kGradientPanel3Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(kGradientPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(kGradientPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(signUpCheckBox)
                    .addComponent(signUpName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(signUpPass, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPasswordField4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(signUpNameField, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(signUpPassField2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(signUpConfirmPass, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(60, Short.MAX_VALUE))
        );
        kGradientPanel3Layout.setVerticalGroup(
            kGradientPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kGradientPanel3Layout.createSequentialGroup()
                .addGap(100, 100, 100)
                .addComponent(signUpTitle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(75, 75, 75)
                .addComponent(signUpName, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(signUpNameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(signUpPass, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPasswordField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(signUpConfirmPass, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(signUpPassField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(signUpCheckBox)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 54, Short.MAX_VALUE)
                .addComponent(kGradientPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(71, 71, 71)
                .addComponent(signUpLogIn)
                .addContainerGap())
        );

        getContentPane().add(kGradientPanel3);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setMinimumSize(new java.awt.Dimension(840, 600));
        jPanel2.setPreferredSize(new java.awt.Dimension(800, 600));
        java.awt.FlowLayout flowLayout1 = new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 0, 0);
        flowLayout1.setAlignOnBaseline(true);
        jPanel2.setLayout(flowLayout1);

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/ui8 Market new illustrations.gif"))); // NOI18N
        jPanel2.add(jLabel7);

        getContentPane().add(jPanel2);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void signUpNameFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_signUpNameFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_signUpNameFieldActionPerformed

    private void signUpCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_signUpCheckBoxActionPerformed
        // TODO add your handling code here:
        if (signUpCheckBox.isSelected()) {
                    // Set password field to display text
                    signUpPassField2.setEchoChar((char)0);
                } else {
                    // Set password field to display asterisks
                    signUpPassField2.setEchoChar('•');
                }
    }//GEN-LAST:event_signUpCheckBoxActionPerformed

    private void jPasswordField4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPasswordField4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jPasswordField4ActionPerformed

    private void signUpLogInMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_signUpLogInMouseClicked
        // TODO add your handling code here:
        if(signUpLogIn.isEnabled()) {
            Main.switchWindow(1);
        }
    }//GEN-LAST:event_signUpLogInMouseClicked

    private void signUpPassField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_signUpPassField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_signUpPassField2ActionPerformed

    private void kGradientPanel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_kGradientPanel4MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_kGradientPanel4MouseClicked

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        // TODO add your handling code here:
        char[] pass1 = jPasswordField4.getPassword();
        char[] pass2 = signUpPassField2.getPassword();
        if (pass1.length != pass2.length) {
            jLabel2.setText("Passwords do not match!");
            signUpPassField2.setText("");
        } else {
            boolean match = true;
            for (int i = 0; i < pass1.length; i++) {
                if (pass1[i] != pass2[i]) {
                    match = false;
                    break;
                }
            }
            if (!match) {
                jLabel2.setText("Passwords do not match!");
                signUpPassField2.setText("");
            }
            else {
                jLabel2.setText("");
                String username = signUpNameField.getText();
                String password = new String(jPasswordField4.getPassword());
                if (username.isEmpty()) {
                    jLabel2.setText("Please enter a username.");
                } else if (password.isEmpty()) {
                    jLabel2.setText("Please enter a password.");
                } else if (usernameExists(username)) {
                    jLabel2.setText("<html> Username already exists! <br> Please choose another username.");
                } else {
                    if (registerUser(username, password)) {
                        Main.openCalendar(username);
                        //Main.openTaskManager(username);
                        dispose();
                    } else {
                        jLabel2.setText("Registration Failed!");
                    }
                }
            }
        }

    }//GEN-LAST:event_jLabel1MouseClicked

    private void jLabel1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jLabel1KeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode()==java.awt.event.KeyEvent.VK_ENTER){
            char[] pass1 = jPasswordField4.getPassword();
            char[] pass2 = signUpPassField2.getPassword();
            if (pass1.length != pass2.length) {
                jLabel2.setText("Passwords do not match!");
                signUpPassField2.setText("");
            } else {
                boolean match = true;
                for (int i = 0; i < pass1.length; i++) {
                    if (pass1[i] != pass2[i]) {
                        match = false;
                        break;
                    }
                }
                if (!match) {
                    jLabel2.setText("Passwords do not match!");
                    signUpPassField2.setText("");
                }
                else {
                    jLabel2.setText("");
                    String username = signUpNameField.getText();
                    String password = new String(jPasswordField4.getPassword());
                    if (username.isEmpty()) {
                        jLabel2.setText("Please enter a username.");
                    } else if (password.isEmpty()) {
                        jLabel2.setText("Please enter a password.");
                    } else if (usernameExists(username)) {
                        jLabel2.setText("<html> Username already exists! <br> Please choose another username.");
                    } else {
                        if (registerUser(username, password)) {
                            Main.openCalendar(username);
                            //Main.openTaskManager(username);
                            dispose();
                        } else {
                            jLabel2.setText("Registration Failed!");
                        }
                    }
                }
            }
        }
    }//GEN-LAST:event_jLabel1KeyPressed

    private static boolean usernameExists(String username) {
        try (BufferedReader reader = new BufferedReader(new FileReader("src/data/account/account.txt"))) {
            String line;
            while ((line = reader.readLine()) != null) {
                String[] parts = line.split(",");
                if (parts.length >= 1 && parts[0].equals(username)) {
                    return true;
                }
            }
        } catch (IOException _) {

        }
        return false;
    }

    private static boolean registerUser(String username, String password) {
        try {
            try (FileWriter fileWriter = new FileWriter("src/data/account/account.txt", true)) {
                fileWriter.write(STR."\{username},\{password}\n");
            }
            return true;
        } catch (IOException e) {
            e.printStackTrace();
            return false;
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPasswordField jPasswordField4;
    private keeptoo.KGradientPanel kGradientPanel3;
    private keeptoo.KGradientPanel kGradientPanel4;
    private javax.swing.JCheckBox signUpCheckBox;
    private javax.swing.JLabel signUpConfirmPass;
    private javax.swing.JLabel signUpLogIn;
    private javax.swing.JLabel signUpName;
    private javax.swing.JTextField signUpNameField;
    private javax.swing.JLabel signUpPass;
    private javax.swing.JPasswordField signUpPassField2;
    private javax.swing.JLabel signUpTitle;
    // End of variables declaration//GEN-END:variables
}
